project:
  type: website
  output-dir: docs

website:
  title: "Rong Xu"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/xurong980623
      - icon: linkedin
        href: https://www.linkedin.com/in/sharon-xu-5a9709326/
      - icon: twitter
        href: https://x.com/SharonXu9823
format:
  html:
    theme: cosmo
    css: styles.css



