project:
  type: website

website:
  title: "Global EV Sales Analysis"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ETC5523-2024/assignment-3-v2-creating-a-blog-xurong980623
format:
  html:
    theme: cosmo
    css: styles.css



